name: flutter_qq
description: Flutter plugin for QQ.
version: 0.0.6
homepage: https://github.com/mdddj/flutter_qq

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  image_picker: ^0.8.4+10

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.github.marekchen.flutterqq
    pluginClass: FlutterQqPlugin


